project:
  type: website
  output-dir: _site
  resources:
    - styles.css          # force-copy this file to the site

website:
  title: "Patrick Hallan"

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    include-in-header:
      text: |
        <style>
          /* Wider layout */
          :root { --content-max-width: 1200px; }
          #quarto-header .container,
          #quarto-header .navbar .container,
          .quarto-container,
          .page-columns .content { max-width: 1200px !important; }

          /* Optional: give content a bit more room vs. side ToC */
          @media (min-width: 992px) {
            .sidebar.sidebar-navigation { flex: 0 0 220px !important; }
          }
        </style>
