project:
  type: website
  output-dir: _site

website:
  title: "Patrick Hallan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
    right:
      - text: "<i class='fa-solid fa-graduation-cap'></i>"
        aria-label: Google Scholar
        href: https://scholar.google.com/
        target: _blank
      - text: "<i class='fa-brands fa-github'></i>"
        aria-label: GitHub
        href: https://github.com/patrickahallan-commits
        target: _blank
      - text: "<i class='fa-brands fa-linkedin'></i>"
        aria-label: LinkedIn
        href: https://www.linkedin.com/
        target: _blank
      - text: "<i class='fa-brands fa-x-twitter'></i>"
        aria-label: X (Twitter)
        href: https://twitter.com/
        target: _blank
  page-footer:
    right: "© {today:yyyy} Patrick Hallan"

format:
  html:
    theme: flatly
    toc: false
    smooth-scroll: true
    include-after-body: profile-sidebar.html
    include-in-header:
      text: |
        <!-- Font Awesome for icons -->
        <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
              integrity="sha512-pvN2oQy2eQkC0kH6m3Qb0g1H8mVbq2rH8G1m8vN1gqf6HkH3kNq1wJQ2w2j7Y1nV0m3nE3cV5E6xH2U3JvYbVA=="
              crossorigin="anonymous" referrerpolicy="no-referrer" />

        <style>
          /* ---------- Site width ---------- */
          :root { --content-max-width: 1200px !important; }
          #quarto-header .container,
          #quarto-header .navbar .container,
          .quarto-container,
          .page-columns,
          .page-columns .content,
          .content,
          .container,
          .container-lg,
          .container-xl,
          .container-xxl { max-width: 1200px !important; }

          /* ---------- Typography / buttons ---------- */
          .btn { padding: .6rem 1.1rem; font-size: 1rem; margin-right: .6rem; }
          .btn + .btn { margin-left: 0; }
          h1, h2, h3 { margin-top: 1.5rem; margin-bottom: .85rem; }
          p { line-height: 1.65; font-size: 1.04rem; }

          /* ---------- Optional hero helpers ---------- */
          .hero { display: flex; gap: 28px; align-items: flex-start; flex-wrap: wrap; }
          .hero img { width: 170px; border-radius: 50%; margin-top: 4px; }
          .hero .hero-body { flex: 1; min-width: 320px; }

          <aside id="profile-sidebar" class="d-none d-lg-block">
  <div class="card shadow-sm">
    <div class="card-body text-center">
      <img src="DSC_7169 (1).jpg" alt="Patrick Hallan" class="profile-photo mb-3">

      <div class="h5 fw-bold mb-1">Patrick Hallan</div>
      <div class="text-muted small mb-3">
        Ph.D. Candidate · Economics<br>University of Utah
      </div>

      <!-- BIO SECTION -->
      <div class="sidebar-bio text-start small">
        <p><strong>University of Utah</strong><br>Department of Economics</p>
        <p>I study international finance, modern imperialism, and international financial subordination.</p>
        <p class="mb-0"><strong>JEL:</strong> F3, F4, E4, B5</p>
      </div>

      <!-- Keep or remove social links -->
      <div class="social-links mt-3">
        <a href="https://scholar.google.com/" target="_blank" aria-label="Google Scholar"><i class="fa-solid fa-graduation-cap"></i></a>
        <a href="https://github.com/patrickahallan-commits" target="_blank" aria-label="GitHub"><i class="fa-brands fa-github"></i></a>
        <a href="https://www.linkedin.com/" target="_blank" aria-label="LinkedIn"><i class="fa-brands fa-linkedin"></i></a>
        <a href="https://twitter.com/" target="_blank" aria-label="X (Twitter)"><i class="fa-brands fa-x-twitter"></i></a>
      </div>
    </div>
  </div>
</aside>
        </style>
