project:
  type: website
  output-dir: _site

website:
  title: "Patrick Hallan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    right: "© {today:yyyy} Patrick Hallan"

format:
  html:
    theme: cosmo
    toc: false          # removes the right “On this page” sidebar
    smooth-scroll: true
    include-in-header:
      text: |
        <style>
          /* widen layout */
          :root { --content-max-width: 1200px !important; }
          #quarto-header .container,
          #quarto-header .navbar .container,
          .quarto-container,
          .page-columns,
          .page-columns .content,
          .content,
          .container,
          .container-lg,
          .container-xl,
          .container-xxl {
            max-width: 1200px !important;
          }
        </style>
