project:
  type: website
  output-dir: _site

website:
  title: "Patrick Hallan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
    right:
      - text: "<i class='fa-solid fa-graduation-cap'></i>"
        aria-label: Google Scholar
        href: https://scholar.google.com/
        target: _blank
      - text: "<i class='fa-brands fa-github'></i>"
        aria-label: GitHub
        href: https://github.com/patrickahallan-commits
        target: _blank
      - text: "<i class='fa-brands fa-linkedin'></i>"
        aria-label: LinkedIn
        href: https://www.linkedin.com/
        target: _blank
      - text: "<i class='fa-brands fa-x-twitter'></i>"
        aria-label: X (Twitter)
        href: https://twitter.com/
        target: _blank
  

format:
  html:
    theme: flatly
    toc: false
    smooth-scroll: true
    include-after-body: profile-sidebar.html
    include-in-header:
      text: |
        <!-- Font Awesome for icons -->
        <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
              integrity="sha512-pvN2oQy2eQkC0kH6m3Qb0g1H8mVbq2rH8G1m8vN1gqf6HkH3kNq1wJQ2w2j7Y1nV0m3nE3cV5E6xH2U3JvYbVA=="
              crossorigin="anonymous" referrerpolicy="no-referrer" />

        <style>
          /* ---------- Site width ---------- */
          :root { --content-max-width: 1200px !important; }
          #quarto-header .container,
          #quarto-header .navbar .container,
          .quarto-container,
          .page-columns,
          .page-columns .content,
          .content,
          .container,
          .container-lg,
          .container-xl,
          .container-xxl { max-width: 1200px !important; }

          /* ---------- Typography / buttons ---------- */
          .btn { padding: .6rem 1.1rem; font-size: 1rem; margin-right: .6rem; }
          .btn + .btn { margin-left: 0; }
          h1, h2, h3 { margin-top: 1.5rem; margin-bottom: .85rem; }
          p { line-height: 1.65; font-size: 1.04rem; }

          /* ---------- Optional hero helpers ---------- */
          .hero { display: flex; gap: 28px; align-items: flex-start; flex-wrap: wrap; }
          .hero img { width: 170px; border-radius: 50%; margin-top: 4px; }
          .hero .hero-body { flex: 1; min-width: 320px; }

          /* ---------- Profile sidebar ---------- */
          #profile-sidebar {
            position: fixed;
            top: 80px;
            left: 60px;
            width: 400px;
            z-index: 100;
          }

          @media (min-width: 992px) {
            .quarto-container { margin-left: 460px; }
          }

          #profile-sidebar .card {
            border-radius: 18px;
            border: none;
            box-shadow: 0 3px 10px rgba(0,0,0,0.08);
          }

          #profile-sidebar .card-body {
            padding: 1.5rem 1.25rem 1rem;
          }

          #profile-sidebar .profile-photo {
            width: 190px;
            height: 190px;
            object-fit: cover;
            object-position: center top;
            border-radius: 50%;
            box-shadow: 0 3px 8px rgba(0,0,0,0.15);
          }

          /* Hide sidebar CV/JMP buttons */
          #profile-sidebar .btn { display: none; }

          /* Bio block */
          #profile-sidebar .sidebar-bio { margin-top: .25rem; }
          #profile-sidebar .sidebar-bio p { margin-bottom: .45rem; line-height: 1.55; }

          
        </style>
