project:
  type: website
  output-dir: _site

website:
  title: "Patrick Hallan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    right: "© {today:yyyy} Patrick Hallan"
  search: false

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    css: styles.css
